kind: Model
apiVersion: v1alpha4
metadata:
  displayName: Matsim
  name: matsim
  type: model
  summary: Matsim model.
  description: >

    Matsim model (release 12.0)

    Requires from upstream models: file /data/inputs/Network_$FUANAME.xml (network), file inputs/Plans_$FUANAME.xml (population)

    Version: https://github.com/JusteRaimbault/UrbanDynamics : commit e862e648cc

spec:
  inputs:
    env:
      - name: FUANAME
        title: FUANAME
        desc:  Name of Functional Urban Area
        type: string
        default: "Exeter"

      - name: SEED
        title: SEED
        desc:  Random seed
        type: integer
        default: 123

      - name: ITERATIONS
        title: ITERATIONS
        desc:  Number of matsim iterations
        type: integer
        default: 5

      - name: THREADS
        title: THREADS
        desc:  Number of parallel threads
        type: integer
        default: 16


  outputs:
    datasets:
      - name: /data/outputs
        type: directory
        desc: Model output.
