kind: Model
apiVersion: v1alpha4
metadata:
  displayName: matsim-1.0-
  name: matsim
  type: model
  summary: Matsim model.
  description: >
    Matsim model.
    Requires from upstream models: file inputs/Network_$FUANAME.xml (network), file inputs/$FUANAME.xml (population)

spec:
  inputs:
    env:
      - name: FUANAME
        title: FUANAME
        desc:  Name of Functional Urban Area
        type: string
        default: "Exeter"

  outputs:
    datasets:
      - name: /data/outputs
        type: directory
        desc: Model output.
