kind: Model
apiVersion: v1alpha4
metadata:
  displayName: Matsim
  name: matsim
  type: model
  summary: Matsim model.
  description: >

    Matsim model (release 12.0)

    Requires from upstream models:
       - files /data/inputs/Network_$FUANAME.xml (network)
       - files /data/inputs/transit_schedule.xml /data/inputs/transit_schedule_$FUANAME.xml /data/inputs/transit_vehicles_$FUANAME.xml (network)
       - file /data/inputs/Plans_$FUANAME.xml (population)

    Version: https://github.com/JusteRaimbault/UrbanDynamics : commit 0bbfdeb108 ; v1.0-UrbanDynamics_0bbfdeb108

spec:
  inputs:
    env:
      - name: FUANAME
        title: FUANAME
        desc:  Name of Functional Urban Area
        type: string
        default: "Exeter"

      - name: SEED
        title: SEED
        desc:  Random seed
        type: integer
        default: 123

      - name: ITERATIONS
        title: ITERATIONS
        desc:  Number of matsim iterations
        type: integer
        default: 5

      - name: THREADS
        title: THREADS
        desc:  Number of parallel threads
        type: integer
        default: 16

      - name: MEMORY
        title: MEMORY
        desc: sbt memory
        type: string
        default: "64G"

      - name: MARGINALUTILITYCAR
        title: MARGINALUTILITYCAR
        desc: choice parameter for mode car
        type: number
        default: -1.0

      - name: MARGINALUTILITYPT
        title: MARGINALUTILITYPT
        desc: choice parameter for mode pt
        type: number
        default: -1.0

      - name: MARGINALUTILITYWALK
        title: MARGINALUTILITYWALK
        desc: choice parameter for mode walk
        type: number
        default: -1.0

  outputs:
    datasets:
      - name: /data/outputs
        type: directory
        desc: Model output.
