kind: Model
apiVersion: v1alpha4
metadata:
  displayName: Matsim Network
  name: matsim-network
  type: model
  summary: Network data preprocessing.
  description: >
    Network data preprocessing for the Matsim model.

    Functional Urban Areas with tile merging.

    TNDS data for public transport, OS open roads for road network

    Version:

      - https://github.com/JusteRaimbault/UrbanDynamics : commit 0a52e7b80f

      - https://github.com/openmole/spatialdata : commit e6a6838f09

      v1.0-UrbanDynamics_0a52e7b80f-spatialdata_e6a6838f09

spec:
  inputs:
    env:
      - name: FUANAME
        title: FUANAME
        desc:  Name of Functional Urban Area
        type: string
        default: "Exeter"

      - name: MEMORY
        title: MEMORY
        desc:  sbt memory
        type: string
        default: "64G"
    dataslots:
      - name: OS Open Roads
        description: >
          OS Open Roads.
        default:
          - uid: d34c5213-e8a7-4107-9825-168f3abb08c7
            versionUid: 2a266819-b8e6-4a05-995c-7b9d76789976
        path: inputs/OSOpenRoads
        required: true

      - name: GHS FUAs
        description: >
          GHS FUAs.
        default:
          - uid: 1bd73b5a-f2d1-4337-8267-2f447ebff2c8
            versionUid: de490541-004f-4c66-88ca-1f8aa39c64ea
        path: inputs/GHSFUAS
        required: true

      - name: OS OpenRoads tiles
        description: >
          OS OpenRoads tiles.
        default:
          - uid: 85977a59-c7f1-4697-b036-849448c9b022
            versionUid: 1dfcc665-067e-400c-9e20-41270f721f72
        path: inputs/OSOpenRoadsTiles
        required: true

      - name: TNDS GTFS
        description: >
          TNDS GTFS.
        default:
          - uid: 3b58701a-537e-4c5b-bd4d-20cb8da40c26
            versionUid: e6d7bb81-8e81-441d-90b0-0b7f2311d265
        path: inputs/TNDS
        required: true


  outputs:
    datasets:
      - name: /data/outputs
        type: directory
        desc: Model output.
