kind: Model
apiVersion: v1alpha3
metadata:
  displayName: saltelli-1.0-
  name: test-openmole
  type: test
  summary: Test OpenMOLE embedding - Saltelli global sensitivity analysis.
  description: >
    Runs OpenMOLE as a model to do a Global Sensitivity Analysis on a dummy model.

spec:
  inputs:
    env:
      - name: SAMPLES
        title: Samples
        desc: Number of samples.
        type: integer
        default: 10000
        min: 100
        max: 100000
      - name: PARALLEL
        title: Parallel
        desc: Number of cores.
        type: integer
        default: 10
        min: 1
        max: 1000
  outputs:
    datasets:
      - name: /data/outputs/saltelli
        type: directory
        desc: Result files.
