kind: Model
apiVersion: v1alpha3
metadata:
  displayName: python-pi-1.0-3bd1fcacd1
  name: python-pi
  type: test
  summary: Monte Carlo computation of Pi in python.
  description: >
    Estimates Pi by drawing uniform points in the unit square.

spec:
  inputs:
    env:
      - name: SAMPLES
        title: Samples
        desc: Number of samples.
        type: integer
        default: 100000
        min: 1000
        max: 10000000
      - name: STEPS
        title: Steps
        desc: Number of steps.
        type: integer
        default: 1000
        min: 1000
        max: 10000
  outputs:
    datasets:
      - name: /data/outputs
        type: directory
        desc: Model output.
