kind: Model
apiVersion: v1alpha4
metadata:
  displayName: Matsim Population
  name: matsim-population
  type: model
  summary: Synthetic population data preprocessing.
  description: >
    Synthetic population preprocessing for the Matsim model.

    Converts SPENSER synthetic population for 2020 to matsim xml plans.

    Version:

      - https://github.com/JusteRaimbault/UrbanDynamics : commit e862e648cc

      - https://github.com/openmole/spatialdata : commit 3bed4bcbe9

spec:
  inputs:
    env:
      - name: FUANAME
        title: FUANAME
        desc:  Name of Functional Urban Area
        type: string
        default: "Exeter"
      - name: SAMPLE
        title: SAMPLE
        desc:  Proportion of population sampled
        type: number
        default: 0.1
    dataslots:
      - name: GHS FUAs
        description: >
          GHS FUAs.
        default:
          - uid: 1bd73b5a-f2d1-4337-8267-2f447ebff2c8
            versionUid: de490541-004f-4c66-88ca-1f8aa39c64ea
        path: inputs/GHSFUAS
        required: true

      - name: Output Areas
        description: >
            Output Areas
        default:
          - uid: db3ed282-26bb-48aa-ba13-5a5d77374a62
            versionUid: 2ccbf1f6-65c1-4278-9416-424f48dba316
        path: inputs/OA
        required: true

      - name: LADistricts
        description: >
          LADistricts.
        default:
          - uid: ec162ec3-e298-446c-a321-17e9daf7acc3
            versionUid: e972dbcc-8718-4b77-afcf-94b3907a5afa
        path: inputs/LADistricts
        required: true

      - name: SPENSER England
        description: >
          SPENSER synthetic population for England.
        default:
          - uid: e372b7a7-db3d-4d09-8d79-30df291b0e0e
            versionUid: e0c68a1e-95d4-43f0-9f6e-4cfa1b25d03b
        path: inputs/SPENSER/England
        required: true

      - name: SPENSER Scotland
        description: >
          SPENSER synthetic population for Scotland.
        default:
          - uid: 5dedbe14-0558-4dba-b74f-35ea3cdcca9f
            versionUid: 29dbd473-91cb-413a-a2db-f5bd4a74d29a
        path: inputs/SPENSER/Scotland
        required: true

      - name: SPENSER Wales
        description: >
          SPENSER synthetic population for Wales.
        default:
          - uid: 1a5aedf4-f7c4-4269-abc0-ec40ddd5ffcd
            versionUid: a99cd6c1-051e-43a5-b27c-2e806cd99a91
        path: inputs/SPENSER/Wales
        required: true

  outputs:
    datasets:
      - name: /data/outputs
        type: directory
        desc: Model output.
