kind: Model
apiVersion: v1alpha4
metadata:
  displayName: Matsim Population
  name: matsim-population
  type: model
  summary: Synthetic population data preprocessing.
  description: >
    Synthetic population preprocessing for the Matsim model.

    Converts SPENSER synthetic population for 2020 to matsim xml plans.

    Version:

      - https://github.com/JusteRaimbault/UrbanDynamics : commit 0a52e7b80f

      - https://github.com/openmole/spatialdata : commit e6a6838f09

      v1.0-UrbanDynamics_0a52e7b80f-spatialdata_e6a6838f09

spec:
  inputs:
    env:
      - name: FUANAME
        title: FUANAME
        desc:  Name of Functional Urban Area
        type: string
        default: "Exeter"

      - name: POPMODE
        title: POPMODE
        desc: Home distribution method (uniform, detailed)
        type: string
        default: "uniform"

      - name: JOBMODE
        title: JOBMODE
        desc: Job distribution method (random, sample, gravity)
        type: string
        default: "random"

      - name: SAMPLE
        title: SAMPLE
        desc:  Proportion of population sampled
        type: number
        default: 0.1

      - name: MEMORY
        title: MEMORY
        desc: sbt memory
        type: string
        default: "64G"
    dataslots:
      - name: GHS FUAs
        description: >
          GHS FUAs.
        default:
          - uid: 1bd73b5a-f2d1-4337-8267-2f447ebff2c8
            versionUid: de490541-004f-4c66-88ca-1f8aa39c64ea
        path: inputs/GHSFUAS
        required: true

      - name: Output Areas
        description: >
            Output Areas
        default:
          - uid: db3ed282-26bb-48aa-ba13-5a5d77374a62
            versionUid: 2ccbf1f6-65c1-4278-9416-424f48dba316
        path: inputs/OA
        required: true

      - name: MSOA
        description: >
            MSOA
        default:
          - uid: a3073246-eb2d-41f9-a224-1de84e8bc963
            versionUid: 3700fc98-8137-45b8-b62d-1187664d505c
        path: inputs/MSOA
        required: true

      - name: LADistricts
        description: >
          LADistricts.
        default:
          - uid: ec162ec3-e298-446c-a321-17e9daf7acc3
            versionUid: e972dbcc-8718-4b77-afcf-94b3907a5afa
        path: inputs/LADistricts
        required: true

      - name: SPENSER England
        description: >
          SPENSER synthetic population for England.
        default:
          - uid: e372b7a7-db3d-4d09-8d79-30df291b0e0e
            versionUid: e0c68a1e-95d4-43f0-9f6e-4cfa1b25d03b
        path: inputs/SPENSER/England
        required: true

      - name: SPENSER Scotland
        description: >
          SPENSER synthetic population for Scotland.
        default:
          - uid: 5dedbe14-0558-4dba-b74f-35ea3cdcca9f
            versionUid: 29dbd473-91cb-413a-a2db-f5bd4a74d29a
        path: inputs/SPENSER/Scotland
        required: true

      - name: SPENSER Wales
        description: >
          SPENSER synthetic population for Wales.
        default:
          - uid: 1a5aedf4-f7c4-4269-abc0-ec40ddd5ffcd
            versionUid: a99cd6c1-051e-43a5-b27c-2e806cd99a91
        path: inputs/SPENSER/Wales
        required: true

      - name: QUANT data
        description: >
          QUANT data.
        default:
          - uid: 232f3312-a4db-44c9-80dc-b0c53bfb33c6
            versionUid: 6a65d56b-400b-47b8-a935-f19449707af2
        path: inputs/QUANT
        required: false

      - name: OSM Buildings England
        description: >
          OSM buildings for England.
        default:
          - uid: 73ca3115-3dc7-4f12-823c-b959865d88fe
            versionUid: 884b3801-d363-4e41-8a54-ffb7fb5e759e
        path: inputs/OSMBuildings/England
        required: false

      - name: OSM Buildings Scotland
        description: >
          OSM buildings for Scotland.
        default:
          - uid: 779e5912-a841-4942-97a3-502845798018
            versionUid: 4ef99ce0-e513-4edd-ae8f-c7b9f1e59283
        path: inputs/OSMBuildings/Scotland
        required: false

      - name: OSM Buildings Wales
        description: >
          OSM buildings for Wales.
        default:
          - uid: 0b28517c-871d-4922-ac1f-867f54882e40
            versionUid: 9f95ef34-2281-4a78-ae0e-3160b3caed69
        path: inputs/OSMBuildings/Wales
        required: false


  outputs:
    datasets:
      - name: /data/outputs
        type: directory
        desc: Model output.
